name: appfuse
description: orchestrator for Flutter apps

homepage: https://github.com/ulughbeck/appfuse
repository: https://github.com/ulughbeck/appfuse
issue_tracker: https://github.com/ulughbeck/appfuse/issues

topics:
  - settings
  - config
  - DI
  - localization
  - theme

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

version: 0.0.1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  package_info_plus: ^9.0.0
  platform_info: ^5.0.0
  permission_handler: ^12.0.1
  http: ^1.6.0

dev_dependencies: 
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
